TrecercoSpedizioni/TrecercoSpedizioni/Controllers/ClienteController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TrecercoSpedizioni.data;
using TrecercoSpedizioni.Models;

namespace TrecercoSpedizioni.Controllers
{
    public class ClienteController : Controller
    {
        private readonly ApplicationDbContext _db;
        public ClienteController(ApplicationDbContext db)
        {
            _db = db;
        }

        //GET
        public IActionResult Index()
        {
            IEnumerable<Cliente> objList = _db.Clienti;
            return View(objList);
        }
        //GET

        public IActionResult Create()
        {
            return View();
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]

        public IActionResult Create(Cliente cliente)
        {
            if (cliente.TipoCliente.ToLower() == "azienda" || cliente.TipoCliente.ToLower() == "privato")
                try
                {


                    string HashedPassword = Password.HashPassword(cliente.Password);
                    cliente.Password = HashedPassword;
                    _db.Clienti.Add(cliente);

                    _db.SaveChanges();
                    TempData["message"] = "Cliente aggiunto con successo";
                    //ritorna a Home Index
                    return RedirectToAction("Index", "Home");
                }

                catch (Exception ex)
                {
                    System.Diagnostics.Debug.WriteLine("ERROREEE" + ex.Message);
                    ModelState.AddModelError("TipoCliente", "Il tipo cliente deve essere azienda o privato");
                }
            return View(cliente);
        }

        //GET
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return View("Error");
            }
            var obj = _db.Clienti.Find(id);
            if (obj == null)
            {
                return View("Error");

            }
            return View(obj);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(Cliente obj)
        {
            if (ModelState.IsValid)
            {
                string HashedPassword = Password.HashPassword(obj.Password);
                obj.Password = HashedPassword;
                _db.Clienti.Update(obj);
                _db.SaveChanges();
                TempData["message"] = "Cliente modificato con successo";
                return RedirectToAction("Index");
            }
            return View(obj);
        }
        //GET
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return View("Error");
            }
            var obj = _db.Clienti.Find(id);
            if (obj == null)
            {
                return View("Error");

            }
            return View(obj);
        }
        //POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeletePost(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var obj = await _db.Clienti.FirstOrDefaultAsync(m => m.idCliente == id);
            if (obj == null)
            {
                return View("Error");

            }
            _db.Clienti.Remove(obj);
            _db.SaveChanges();
            TempData["error"] = "Cliente eliminato con successo";
            return RedirectToAction("Index");
        }
        //GET
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _db.Clienti
                .FirstOrDefaultAsync(m => m.idCliente == id);
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);

        }
    }
}

TrecercoSpedizioni/TrecercoSpedizioni/Controllers/LoginController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using TrecercoSpedizioni.data;
using TrecercoSpedizioni.Models;

namespace TrecercoSpedizioni.Controllers
{
    public class LoginController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IAuthenticationSchemeProvider _schemeProvider;

        public LoginController(ApplicationDbContext context, IAuthenticationSchemeProvider schemeProvider)
        {
            _db = context;
            _schemeProvider = schemeProvider;
        }
        //GET
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(Login login)
        {
            Cliente? cliente = _db.Clienti.SingleOrDefault(x => x.Username == login.Username);

            if (cliente == null)
            {
                TempData["error"] = "Non esiste questo account";
                return View();

            }
            if (Password.VerifyPassword(login.Password, cliente.Password))
            {
                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name, cliente.Username),
                    new Claim(ClaimTypes.Role, cliente.Usertype)
                };

                var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

                var authProperties = new AuthenticationProperties();

                await HttpContext.SignInAsync(
                        CookieAuthenticationDefaults.AuthenticationScheme,
                        new ClaimsPrincipal(claimsIdentity),
                        authProperties);
                TempData["success"] = "Login effettuato";
                return RedirectToAction("Index", "Home");
            }
            else
            {
                TempData["error"] = "Password sbagliata";
            }
            return View();
        }


        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            TempData["message"] = "Logout effettuato";
            return RedirectToAction("Index", "Home");

        }
        public IActionResult Register()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Register([Bind("Username,Password,TipoCliente,Nome,CodiceFiscale,PartitaIva")] Cliente cliente)
        {
            if (cliente.TipoCliente.ToLower() == "azienda" || cliente.TipoCliente.ToLower() == "privato")
                try
                {


                    string HashedPassword = Password.HashPassword(cliente.Password);
                    cliente.Password = HashedPassword;
                    _db.Clienti.Add(cliente);

                    _db.SaveChanges();
                    TempData["message"] = "Cliente aggiunto con successo";
                    //ritorna a Home Index
                    return RedirectToAction("Index", "Home");
                }

                catch (Exception ex)
                {
                    System.Diagnostics.Debug.WriteLine("ERROREEE" + ex.Message);
                    ModelState.AddModelError("TipoCliente", "Il tipo cliente deve essere azienda o privato");
                }
            return View(cliente);
        }
    }
}

TrecercoSpedizioni/TrecercoSpedizioni/Controllers/SpedizioniController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TrecercoSpedizioni.data;
using TrecercoSpedizioni.Models;

namespace TrecercoSpedizioni.Controllers
{
    public class SpedizioniController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SpedizioniController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Spedizonis
        public IActionResult Index()
        {
            IEnumerable<Spedizioni> objList = _context.Spedizioni.Include(c => c.Cliente);
            return View(objList);
        }

        // GET: Spedizonis/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shipping = await _context.Spedizioni.Include(s => s.Cliente).Include(s => s.DettagliSpedizioni).FirstOrDefaultAsync(m => m.Id == id);
            if (shipping == null)
            {
                return NotFound();
            }

            return View(shipping);
        }

        // GET: Spedizonis/Create
        public IActionResult Create()
        {
            if (ViewBag.NomeCliente == null)
            {
                ViewBag.NomeCliente = new SelectList(_context.Clienti, "idCliente", "Nome");
            }


            return View();
        }

        // POST: Spedizonis/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdCliente,DataSpedizione,Peso,IndirizzoDestinatario,CittaDestinazione,NominativoDestinatario,CostoSpedizione,DataConsegnaPrevista")] Spedizioni spedizioni)
        {
            try
            {
                spedizioni.Id = Guid.NewGuid();
                _context.Add(spedizioni);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {

                System.Diagnostics.Debug.WriteLine("ERROREEE" + ex.Message);
                System.Diagnostics.Debug.WriteLine(ex.Message);
                System.Diagnostics.Debug.WriteLine(ex.StackTrace);

                return View(spedizioni);
            }
        }

        // GET: Spedizonis/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var spedizoni = await _context.Spedizioni.FindAsync(id);
            if (spedizoni == null)
            {
                return NotFound();
            }


            return View(spedizoni);
        }

        // POST: Spedizonis/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,IdCliente,DataSpedizione,Peso,CittaDestinazione,IndirizzoDestinatario,NominativoDestinatario,CostoSpedizione,DataConsegnaPrevista")] Spedizioni spedizioni)
        {
            if (id != spedizioni.Id)
            {
                return NotFound();
            }

            try
            {
                _context.Update(spedizioni);
                await _context.SaveChangesAsync();
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine("ERROREEE" + ex.Message);
                System.Diagnostics.Debug.WriteLine(ex.Message);
                System.Diagnostics.Debug.WriteLine(ex.StackTrace);
            }
            return RedirectToAction("Index");
        }

        // GET: Spedizonis/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var spedizioni = await _context.Spedizioni
                .FirstOrDefaultAsync(m => m.Id == id);
            if (spedizioni == null)
            {
                return NotFound();
            }

            return View(spedizioni);
        }

        // POST: Spedizonis/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var spedizoni = await _context.Spedizioni.FindAsync(id);
            if (spedizoni != null)
            {
                _context.Spedizioni.Remove(spedizoni);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SpedizoniExists(Guid id)
        {
            return _context.Spedizioni.Any(e => e.Id == id);
        }
    }
}

TrecercoSpedizioni/TrecercoSpedizioni/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Trecerco Spedizioni</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="~/TrecercoSpedizioni.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/image/logo_trial.png" alt="Logo" height="100px" width="150px"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        
                        @{
                            if (User.IsInRole("admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Cliente" asp-action="Index">Lista Clienti</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Spedizioni" asp-action="Index">Spedizioni</a>
                                </li>
                            }
                        }
                        @{
                            if (User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Logout">Logout</a>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Login">Login</a>
                                </li>
                            }
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_PartialView" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - TrecercoSpedizioni - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TrecercoSpedizioni/TrecercoSpedizioni/Views/Shared/_PartialView.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}
@if (TempData["message"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.info('@TempData["message"]');
    </script>
}